[package]
name = "grub-split-library"
version = "0.1.0"
authors = ["Thomas Smith"]
edition = "2021"

[dependencies]
grub-split-macros = { path = "../macros" }

log = "0.4"
proc-maps = "0.3.0"
read-process-memory = "0.1.5"
