name: Rust CI

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Format
      run: cargo fmt --check --all --verbose
