name: Rust CI

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install nightly --profile minimal
    - name: Build
      run: cargo build --verbose
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install nightly --profile minimal
    - name: Build
      run: cargo build --release --verbose
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install nightly --component rustfmt
    - name: Check format
      run: cargo fmt --check --all --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install nightly --component clippy
    - name: Run Clippy
      run: cargo clippy --verbose
